Roles
IFSP-Campus-Itapetininga/sexta-e-nois-backend pull request #22
Opened 2022-11-08 05:44 UTC by gabrielBFerreira

- adicionadas rotas de criar e listar roles (papeis)
- adicionadas seeds (dados padrão) para tabelas de usuario e papel
- alterado nome do role nas rotas de evento

2022-11-13 15:19 UTC, Pelegrinetti requested changes

2022-11-13 15:19 UTC, Pelegrinetti commented on src/data/seeds/users.js
> +      nome: 'admin001',
```suggestion
      nome: 'Administrador',
```
Esse é o nome ou o `"username"` de login?

2022-11-13 15:19 UTC, Pelegrinetti commented on src/data/seeds/users.js
> +      senha: '$2a$12$FM1lVPdMgQzYmPu8T8oqIebElMhz2TwiCYzO5z24RM20bMccT6gTu', // password = 123; NÃO USAR este usuário em produção; apenas para testes; apagar este arquivo ao final do projeto.
```suggestion
      senha: process.env.ADMIN_PASSWORD,
```
Melhor nem arriscar deixar isso no código.

2022-11-13 15:19 UTC, Pelegrinetti commented on src/modules/roles/controllers/roles.js
> +const Role = require('../models/Role')
Acredito que não seja o caso de deixar a `role` ser criável, não sei se isso foi discutido antes, mas hoje os middlewares usam o texto para limitar o uso do sistema. Se a pessoal criar um novo papel será bloqueado por todas as rotas.

2022-11-14 07:14 UTC, gabrielBFerreira commented on src/data/seeds/users.js
> +      nome: 'admin001',
Era o username, mas com a adição do campo nome, será o nome.

2022-11-14 07:15 UTC, gabrielBFerreira commented on src/modules/roles/controllers/roles.js
> +const Role = require('../models/Role')
Realmente. Essa rota criei para possível uso futuro, mas posso desabilitá-la.

2022-11-14 07:39 UTC, merged