Feature/questionario 2
IFSP-Campus-Itapetininga/sexta-e-nois-backend pull request #23
Opened 2022-11-09 23:16 UTC by sav5rv

CRUD questionario, profissionais

2022-11-11 07:07 UTC, gabrielBFerreira requested changes
Bom trabalho!
Apontei algumas mudanças às quais você deve se atentar.
Qualquer dúvida sobre os comentários, pode me chamar!

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/data/migrations/20221023014757_tb_aluno.js
> +  return knex.schema.createTable('tb_aluno', (table) => {
No padrão que estamos usando, não precisaria do prefixo `tb_`, ficando apenas `aluno`. Alterar o nome também no método `exports.down` e na Model.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/data/migrations/20221023014757_tb_aluno.js
> +    table.integer('id_usuario').unsigned()
Aqui, pode-se utilizar o padrão camelCase
de `id_usuario` para `idUsuario`
Atentar-se à isso em todos os campos da tabela onde haja um `_`.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/data/migrations/20221023014757_tb_aluno.js
> +    table.foreign('id_usuario').references('tb_usuario.id')
o nome da tabela de usuários será apenas `usuario`, sem o `tb_`.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/data/migrations/20221023015819_tb_prof.js
> +    return knex.schema.createTable('tb_prof', (table) => {
Mesma ideia das outras tabelas, remover o `tb_` do nome da tabela e usar camelCase nos nomes dos campos.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/data/migrations/20221023020112_tb_grp.js
> +    return knex.schema.createTable('tb_grp', (table) => {
Mesma ideia das outras tabelas, remover o `tb_` do nome da tabela e usar camelCase nos nomes dos campos.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/data/migrations/20221023030649_tb_aluno2.js
> +    return knex.schema.createTable('tb_aluno2', (table) => {
Esta tabela `aluno2` seria para que? Se for apenas uma versão 'melhorada' da tabela aluno, manter apenas a mais atualizada e remover o '2' do nome; caso seja outro motivo, desconsiderar este comentário.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/data/migrations/20221023142511_tb_quest.js
> +  return knex.schema.createTable('tb_quest', (table) => {
Mesma ideia das outras tabelas, remover o `tb_` do nome da tabela e usar camelCase nos nomes dos campos.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/data/migrations/20221030003309_usuario.js
> +return knex.schema.createTable('tb_usuario', (table) => {
A tabela usuário não será necessária aqui, pois ela estará disponível em breve junto ao módulo de login; portanto, pode descartar esta migration.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/data/migrations/20221030032251_tb_resp.js
> +    return knex.schema.createTable('tb_resp', (table) => {
Mesma ideia das outras tabelas, remover o `tb_` do nome da tabela e usar camelCase nos nomes dos campos.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/data/migrations/20221023014757_tb_aluno.js
> +  return knex.schema.createTable('tb_aluno', (table) => {
Mais um detalhe: verifique se não haverá outro grupo já criando uma tabela `aluno` (creio que o módulo do André tenha isso); a ideia é que apenas um crie.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/aluno/controllers/aluno.js
> +}
esta função teste pode ser removida, tanto daqui como da exportação lá embaixo.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/aluno/controllers/aluno.js
> +    res.send('criando usuário!')
Caso queira colocar mesmo esta mensagem, junte-a com o `res.status(201).send()` da linha de baixo, ficando `res.status(201).send({message: 'Criando usuário!'})`.
No entanto, repare que a criação de usuário é uma outra rota, que está no módulo de usuários, então talvez seja o caso de colocar outra mensagem.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/aluno/controllers/aluno.js
> +const Aluno = require('../models/Aluno')
Para o código estamos usando o inglês, deixando apenas o banco em português, por isso, recomendaria que troque `Aluno` por `Student`, tanto aqui como na Model e nos nomes dos arquivos.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/aluno/controllers/aluno.js
> +    const aluno = await alunoModel.list()
Por se tratar de uma lista, pode-se usar o plural aqui
`const alunos` ou `const students` (caso siga a dica do idioma citada acima)

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/aluno/models/Aluno.js
> +    if (!result) { throw new Error('Aluno not found') }
Creio que o ideal seja mudar a nomenclatura para o inglês mesmo, aí aqui ficaria `Student not found`

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/aluno/routes.js
> +router.get('/teste',  alunoController.teste)
Esta pode ser removida.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/grp/controllers/grp.js
> +    res.send('criando grupo!')
Seguir mesma dica do outro arquivo, colocar mensagens junto ao `res.status`.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/grp/controllers/grp.js
> +    const grp = await grpModel.list()
Creio que aqui seria `grps`

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/grp/routes.js
> +router.get('/teste',  grpController.teste)
Esta pode ser removida.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/grp/controllers/grp.js
> +}
Remover funções teste.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/perg/controllers/perg.js
> +const Perg = require('../models/Perg')
Seguindo a nomenclatura em inglês, creio que o nome para este módulo seja `Question`

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/perg/controllers/perg.js
> +}
Remover funções teste.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/perg/controllers/perg.js
> +    res.status(201).send()
Colocar mensagem no `res.status`.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/perg/routes.js
> +router.get('/teste',  pergController.teste)
Remover rota teste.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/prof/controllers/prof.js
> +}
Remover função teste.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/prof/controllers/prof.js
> +    res.send('criando profissional!')
Colocar mensagem no `res.status`.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/prof/controllers/prof.js
> +    const prof = await profModel.list()
`const profs`

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/perg/controllers/perg.js
> +    const perg = await pergModel.list()
`const pergs` ou `const questions`

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/prof/models/Prof.js
> +    if (!result) { throw new Error('Profissional not found') }
`Professional not found`

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/prof/routes.js
> +router.get('/teste',  profController.teste)
Remover rota teste

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/quest/controllers/quest.js
> +const Quest = require('../models/Quest')
Creio que este seria o módulo `Questionnaire`

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/quest/controllers/quest.js
> +    const quest = await questModel.list()
`const quests` ou `const questionnaires`

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/quest/controllers/quest.js
> +}
Remover função teste.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/quest/models/Quest.js
> +    if (!result) { throw new Error('Quest not found') }
`Questionnaire not found` (ou, se o caso aqui for buscar uma pergunta apenas e não o questionário todo, `Question not found`).

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/quest/routes.js
> +router.get('/teste',  questController.teste)
Remover rota teste.

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/quest/routes.js
> +const ROUTES_PREFIX = '/quest'
`/questionnaires`

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/grp/routes.js
> +const ROUTES_PREFIX = '/grp'
Creio que o ideal seria `/groups`

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/perg/routes.js
> +const ROUTES_PREFIX = '/perg'
`/questions`

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/prof/routes.js
> +const ROUTES_PREFIX = '/prof'
`/professionals`

2022-11-11 07:07 UTC, gabrielBFerreira commented on src/modules/aluno/routes.js
> +const ROUTES_PREFIX = '/aluno'
`/students`

2022-11-16 18:00 UTC, sav5rv commented on src/modules/quest/routes.js
> +router.get('/teste',  questController.teste)
Feito

2022-11-16 18:01 UTC, sav5rv commented on src/modules/quest/controllers/quest.js
> +}
Feito

2022-11-16 18:01 UTC, sav5rv commented on src/modules/prof/routes.js
> +router.get('/teste',  profController.teste)
Feito

2022-11-16 18:02 UTC, sav5rv commented on src/modules/prof/controllers/prof.js
> +}
Feito

2022-11-16 18:02 UTC, sav5rv commented on src/modules/perg/routes.js
> +router.get('/teste',  pergController.teste)
Feito

2022-11-16 18:02 UTC, sav5rv commented on src/modules/perg/controllers/perg.js
> +}
Feito

2022-11-16 18:02 UTC, sav5rv commented on src/modules/grp/controllers/grp.js
> +}
Feito

2022-11-16 18:02 UTC, sav5rv commented on src/modules/grp/routes.js
> +router.get('/teste',  grpController.teste)
Feito

2022-11-16 18:03 UTC, sav5rv commented on src/modules/aluno/routes.js
> +router.get('/teste',  alunoController.teste)
Feito

2022-11-16 18:03 UTC, sav5rv commented on src/modules/aluno/controllers/aluno.js
> +}
Feito

2022-11-16 18:04 UTC, sav5rv commented on src/data/migrations/20221023030649_tb_aluno2.js
> +    return knex.schema.createTable('tb_aluno2', (table) => {
Feito

2022-11-16 18:04 UTC, sav5rv commented on src/data/migrations/20221023014757_tb_aluno.js
> +    table.integer('id_usuario').unsigned()
Feito

2022-11-16 18:05 UTC, sav5rv commented on src/data/migrations/20221023014757_tb_aluno.js
> +  return knex.schema.createTable('tb_aluno', (table) => {
o "tb" no inicio do nome me auxilia a identif que ali devo usar uma tabela. Mudei para tbAluno.

2022-11-16 18:06 UTC, sav5rv commented on src/data/migrations/20221023014757_tb_aluno.js
> +    table.foreign('id_usuario').references('tb_usuario.id')
o "tb" no inicio do nome me auxilia a identif que ali devo usar uma tabela. Mudei para tbUsuario.

2022-11-16 18:06 UTC, sav5rv commented on src/data/migrations/20221023015819_tb_prof.js
> +    return knex.schema.createTable('tb_prof', (table) => {
o "tb" no inicio do nome me auxilia a identif que ali devo usar uma tabela. Mudei para tbProf.

2022-11-16 18:06 UTC, sav5rv commented on src/data/migrations/20221023020112_tb_grp.js
> +    return knex.schema.createTable('tb_grp', (table) => {
o "tb" no inicio do nome me auxilia a identif que ali devo usar uma tabela. Mudei para tbGrp.

2022-11-16 18:07 UTC, sav5rv commented on src/data/migrations/20221023142511_tb_quest.js
> +  return knex.schema.createTable('tb_quest', (table) => {
o "tb" no inicio do nome me auxilia a identif que ali devo usar uma tabela. Mudei para tbQuest.

2022-11-16 18:07 UTC, sav5rv commented on src/data/migrations/20221030032251_tb_resp.js
> +    return knex.schema.createTable('tb_resp', (table) => {
o "tb" no inicio do nome me auxilia a identif que ali devo usar uma tabela. Mudei para tbResp.

2022-11-16 23:32 UTC, gabrielBFerreira requested changes

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/data/migrations/20221023020112_tbGrp.js
> +    return knex.schema.createTable('tbGrp', (table) => {
```suggestion
    return knex.schema.createTable('grupo', (table) => {
```

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/data/migrations/20221023020112_tbGrp.js
> +        table.foreign('idProf').references('tbProf.id')
Você pode remover as chaves estrangeiras das migrations, pois necessitará que as tabelas dos outros grupos já existam; então, quando estiverem alinhados, você cria novas migrations para alterar as tabelas e adicionar os campos que serão chaves estrangeiras, já com o nome certo da tabela do grupo irmão.

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/data/migrations/20221023020112_tbGrp.js
> +    return knex.schema.dropTable('tbGrp')
```suggestion
    return knex.schema.dropTable('grupo')
```

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/data/migrations/20221023142511_tbQuest.js
> +  return knex.schema.createTable('tbQuest', (table) => {
```suggestion
  return knex.schema.createTable('questionario', (table) => {
```

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/data/migrations/20221023142511_tbQuest.js
> +    table.foreign('idGrp').references('tbGrp.id')
```suggestion
    table.foreign('idGrp').references('grupo.id')
```

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/data/migrations/20221023142511_tbQuest.js
> +  return knex.schema.dropTable('tbQuest')
```suggestion
  return knex.schema.dropTable('questionario')
```

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/data/migrations/20221030032251_tbResp.js
> +    return knex.schema.createTable('tbResp', (table) => {
```suggestion
    return knex.schema.createTable('resposta', (table) => {
```

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/data/migrations/20221030032251_tbResp.js
> +        table.foreign('idQuest').references('tbQuest.id')
```suggestion
        table.foreign('idQuest').references('questionario.id')
```

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/data/migrations/20221030032251_tbResp.js
> +  return knex.schema.dropTable('tbResp')
```suggestion
  return knex.schema.dropTable('resposta')
```

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/modules/grp/models/Grp.js
> +  const TABLE_NAME = 'tbGrp'
```suggestion
  const TABLE_NAME = 'grupo'
```

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/modules/perg/models/Perg.js
> +  const TABLE_NAME = 'tb_perg'
Esta migration não está no commit, criar ela com o nome da tabela sendo `pergunta`

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/modules/perg/models/Perg.js
> +  const TABLE_NAME = 'tb_perg'
```suggestion
  const TABLE_NAME = 'pergunta'
```

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/modules/perg/models/Perg.js
> +    if (!result) { throw new Error('Pergunta not found') }
```suggestion
    if (!result) { throw new Error('Question not found') }
```

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/data/migrations/20221023142511_tbQuest.js
> +    table.string('pergunta').nullable()
Este campo não seria aqui, mas sim na tabela `pergunta` que será criada (que inclusive deverá ter uma chave estrangeira desta tabela `questionario`)

2022-11-16 23:32 UTC, gabrielBFerreira commented on src/modules/quest/models/Quest.js
> +  const TABLE_NAME = 'tbQuest'
```suggestion
  const TABLE_NAME = 'questionario'
```

2022-11-28 00:50 UTC, sav5rv commented on src/data/migrations/20221030003309_usuario.js
> +return knex.schema.createTable('tb_usuario', (table) => {
tb removida

2022-11-28 00:50 UTC, sav5rv commented on src/data/migrations/20221023014757_tb_aluno.js
> +  return knex.schema.createTable('tb_aluno', (table) => {
tb removida, outro grupo está fazendo

2022-11-28 00:58 UTC, sav5rv commented on src/modules/quest/routes.js
> +const ROUTES_PREFIX = '/quest'
feito

2022-11-28 00:58 UTC, sav5rv commented on src/modules/grp/routes.js
> +const ROUTES_PREFIX = '/grp'
feito

2022-11-28 00:59 UTC, sav5rv commented on src/modules/perg/routes.js
> +const ROUTES_PREFIX = '/perg'
feito

2022-11-28 00:59 UTC, sav5rv commented on src/modules/prof/routes.js
> +const ROUTES_PREFIX = '/prof'
essa tb foi excluída

2022-11-28 01:00 UTC, sav5rv commented on src/modules/aluno/routes.js
> +const ROUTES_PREFIX = '/aluno'
essa tb foi excluída

2022-11-28 01:00 UTC, sav5rv commented on src/data/migrations/20221023020112_tbGrp.js
> +        table.foreign('idProf').references('tbProf.id')
removi as chaves estrangeiras das minhas migrations

2022-11-28 01:02 UTC, sav5rv commented on src/modules/aluno/controllers/aluno.js
> +const Aluno = require('../models/Aluno')
essa tb foi removida

2022-11-28 01:03 UTC, sav5rv commented on src/modules/aluno/controllers/aluno.js
> +    const aluno = await alunoModel.list()
essa tb foi removida

2022-11-28 01:03 UTC, sav5rv commented on src/modules/aluno/models/Aluno.js
> +    if (!result) { throw new Error('Aluno not found') }
essa tb foi removida

2022-11-28 01:05 UTC, sav5rv commented on src/modules/grp/controllers/grp.js
> +    const grp = await grpModel.list()
feito

2022-11-28 01:07 UTC, sav5rv commented on src/modules/prof/controllers/prof.js
> +    const prof = await profModel.list()
essa tb foi removida

2022-11-28 01:07 UTC, sav5rv commented on src/modules/prof/models/Prof.js
> +    if (!result) { throw new Error('Profissional not found') }
essa tb foi remvida

2022-11-29 16:04 UTC, sav5rv commented on src/modules/aluno/controllers/aluno.js
> +    res.send('criando usuário!')
módulo aluno removido

2022-11-29 16:06 UTC, sav5rv commented on src/modules/grp/controllers/grp.js
> +    res.send('criando grupo!')
corrigido para res.status(201).send()

2022-11-29 16:08 UTC, sav5rv commented on src/modules/perg/controllers/perg.js
> +    res.status(201).send()
corrigido para res.status(201).send()

2022-11-29 16:08 UTC, sav5rv commented on src/modules/prof/controllers/prof.js
> +    res.send('criando profissional!')
esse módulo foi removido

2022-11-29 16:10 UTC, sav5rv commented on src/modules/quest/models/Quest.js
> +    if (!result) { throw new Error('Quest not found') }
corrigido

2022-11-29 16:19 UTC, sav5rv commented on src/modules/quest/controllers/quest.js
> +    const quest = await questModel.list()
feito

2022-11-29 16:25 UTC, sav5rv commented on src/modules/perg/controllers/perg.js
> +const Perg = require('../models/Perg')
feito

2022-11-29 16:26 UTC, sav5rv commented on src/modules/quest/controllers/quest.js
> +const Quest = require('../models/Quest')
irmão esse mantive Quest

2022-11-29 16:27 UTC, sav5rv commented on src/modules/perg/models/Perg.js
> +  const TABLE_NAME = 'tb_perg'
ESSA NÃO ENTENDI!

2022-11-30 02:27 UTC, gabrielBFerreira requested changes

2022-11-30 02:27 UTC, gabrielBFerreira commented on src/modules/perg/models/Perg.js
> +  const TABLE_NAME = 'tbQuest'
Ou este ou o `/models/Quest,js` estão errados, pois ambos estão usando a mesma tabela (`questionario`).
Ao mesmo tempo, nenhum está usando a tabela `resposta`.

2022-12-05 14:09 UTC, gabrielBFerreira approved these changes
De acordo com @sav5rv, foram verificadas as models e tabelas, e não serão alteradas. Sendo assim, aprovo a PR.

2022-12-05 14:10 UTC, merged