Feat/marmitas pedido list
IFSP-Campus-Itapetininga/sexta-e-nois-backend pull request #25
Opened 2022-11-15 22:41 UTC by nishiduka

- Corrigido listagem com filtro
- Refatorado busca de produtos por order

2022-11-16 03:15 UTC, gabrielBFerreira requested changes
Nice work!
Encontrei um errinho de escrita no nome da função, mas só isso msm
Apontei ali no comentário

2022-11-16 03:15 UTC, gabrielBFerreira commented on src/modules/lunchs/models/Order.js
> +  const retriveProductsFromOrder = async (ids = []) => {
```suggestion
  const retrieveProductsFromOrder = async (ids = []) => {
```
faltou um 'e' no retrieve

2022-11-16 03:15 UTC, gabrielBFerreira commented on src/modules/lunchs/models/Order.js
> +    const products = await retriveProductsFromOrder(ids)
```suggestion
    const products = await retrieveProductsFromOrder(ids)
```

2022-11-21 22:02 UTC, dogustavo approved these changes

2022-11-21 22:02 UTC, merged