Feature/inventory
IFSP-Campus-Itapetininga/sexta-e-nois-backend pull request #26
Opened 2022-11-20 17:42 UTC by xocky2

Criado todas as rotas do fornecedor, inventário e migrations das respectivas tabelas.

2022-11-22 02:14 UTC, nishiduka commented on src/modules/inventory/controllers/inventory.js
> +        return {
aqui poderia ter feito somente um
```
return {
... transaction,
parseInt(transaction.quantidade)
}
```

2022-11-22 15:06 UTC, gabrielBFerreira commented
@xocky2 
Ainda não revisei, mas achei uma coisa aqui: desfaça a exclusão do `.env.example`, esse arquivo deve continuar lá, creio q vc renomeou-o para .env localmente e o git entendeu q vc apagou o original.

2022-11-26 22:35 UTC, xocky2 commented on src/modules/inventory/controllers/inventory.js
> +        return {
Resolvido

2022-11-27 23:43 UTC, gabrielBFerreira requested changes

2022-11-27 23:43 UTC, gabrielBFerreira commented on .env.example
> +JWT_SECRET=secret-md5-hash
```suggestion

```

2022-11-27 23:43 UTC, gabrielBFerreira commented on .env.example
> +ADMIN_PASSWORD=create-md5-hashed-pwd-here
```suggestion

```

2022-11-27 23:43 UTC, gabrielBFerreira commented on src/data/migrations/20221111213418_createTableContact.js
> +  return knex.schema.createTable('contato', (table) => {
```suggestion
  return knex.schema.createTable('contatoFornecedor', (table) => {
```

2022-11-27 23:43 UTC, gabrielBFerreira commented on src/data/migrations/20221111213418_createTableContact.js
> +  return knex.schema.dropTable('inventory_vendor_contact2')
```suggestion
  return knex.schema.dropTable('contatoFornecedor')
```

2022-11-27 23:43 UTC, gabrielBFerreira commented on src/data/migrations/20221111213532_createTableAddress.js
> +  return knex.schema.createTable('endereco', (table) => {
```suggestion
  return knex.schema.createTable('enderecoFornecedor', (table) => {
```

2022-11-27 23:43 UTC, gabrielBFerreira commented on src/data/migrations/20221111213532_createTableAddress.js
> +  return knex.schema.dropTable('endereco')
```suggestion
  return knex.schema.dropTable('enderecoFornecedor')
```

2022-11-27 23:43 UTC, gabrielBFerreira commented on src/modules/vendor/models/Address.js
> +  const TABLE_NAME = 'endereco'
```suggestion
  const TABLE_NAME = 'enderecoFornecedor'
```

2022-11-27 23:43 UTC, gabrielBFerreira commented on src/modules/vendor/models/Contact.js
> +  const TABLE_NAME = 'contato'
```suggestion
  const TABLE_NAME = 'contatoFornecedor'
```

2022-11-27 23:49 UTC, gabrielBFerreira approved these changes

2022-11-27 23:49 UTC, merged