Modulo de secretaria
IFSP-Campus-Itapetininga/sexta-e-nois-backend pull request #27
Opened 2022-11-21 22:48 UTC by WalaceSoares

por enquanto envolvendo estudante e responsável
criado as rotas de estudantes e responsável
criado controllers estudante e responsável
criado models estudante e responsável
criado validação dos campos

2022-11-22 02:18 UTC, nishiduka approved these changes

2022-11-22 15:02 UTC, gabrielBFerreira requested changes

2022-11-22 15:02 UTC, gabrielBFerreira commented on src/modules/secretary/controllers/responsible.js
> +    const students = await responsibleModel.list()
aqui é students mesmo ou responsibles? 
ou é aquela rota que vc puxa os estudantes pra trazer os responsáveis q vc havia comentado?

2022-11-22 15:02 UTC, gabrielBFerreira commented on src/modules/secretary/controllers/student.js
> +const Aluno = require('../models/Student')
aqui pode ser Student pra seguir o padrão do outro model

2022-11-22 15:02 UTC, gabrielBFerreira commented on src/modules/secretary/controllers/student.js
> +const alunoModel = Aluno()
e studentModel

2022-11-22 22:35 UTC, WalaceSoares commented on src/modules/secretary/controllers/responsible.js
> +    const students = await responsibleModel.list()
ela puxa o aluno junto mas é necessário alteração para responsible mesmo

2022-11-22 22:35 UTC, WalaceSoares commented on src/modules/secretary/controllers/student.js
> +const Aluno = require('../models/Student')
alterado para seguir o padrão

2022-11-22 22:36 UTC, WalaceSoares commented on src/modules/secretary/controllers/student.js
> +const alunoModel = Aluno()
também alterado

2022-11-23 03:20 UTC, gabrielBFerreira approved these changes

2022-11-23 22:36 UTC, merged